---
- name: Restart WireGuard
  ansible.builtin.systemd:
    name: "wg-quick@{{ item.network_name }}"
    enabled: yes
    state: restarted
  loop: "{{ wireguard_networks }}"
  tags: ansible-role-wireguard
